# This should be inside my-project/netlify.toml

[build]
  command = "npm run build"
  publish = "build/client"  # Or dist/client, depending on your build output
  functions = "netlify/functions"

# THIS IS THE CRITICAL PART THAT FIXES THE "PAGE NOT FOUND" ERROR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
